# scripts-ros :: manifest.rsc
# GENERATED by tools/gen_manifest.py -- do not edit by hand.
# md5 of every updatable file, so the router can detect an upstream
# change with a single fetch instead of downloading each script.

:global mManifest {
    "lists/engine.rsc"="8372da7628a59e684985dc218a488f55";
    "lists/FWD_update_list.rsc"="403c16cff1bc50acde97af61129928b3";
    "lists/FWD_update_RU_list.rsc"="ad6ce4e956628aea4bbbf38c1886e298";
    "lists/IP_MihomoProxyRoS_list.rsc"="3d9cb910c8af38c46e19fd543b01a586";
    "lists/route_UP.rsc"="9b96513e0cc56dd7756ecb8b61223c3c";
    "assets/changeDNS.rsc"="7e555aa8edefea6282bd8008d37bb7b1";
    "assets/repull.rsc"="b6b323c1d9876baa22b098d5c819d433";
    "assets/ca/sslcom-ecc-root.pem"="dd4f1313c25244f380fc807d5f173ef7"
}
