#!/usr/bin/env python3
"""Regenerate manifest.rsc -- an md5 of every file the installer can update.

The router fetches this one small file to learn whether anything upstream has
moved, instead of downloading four scripts just to compare them. Run it before
every commit that touches lists/ or assets/:

    python tools/gen_manifest.py
"""
import hashlib, pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
TRACKED = ["lists", "assets"]
CRLF = b"\r\n"


def main():
    rows = []
    for folder in TRACKED:
        for path in sorted((ROOT / folder).glob("*.rsc")):
            data = path.read_bytes()
            # RouterOS hashes the bytes it fetched. A CRLF checkout would hash
            # differently on every machine and quietly break update detection,
            # so refuse rather than publish a digest nobody can reproduce.
            if CRLF in data:
                raise SystemExit(f"{path} has CRLF line endings; convert to LF and rerun")
            rows.append((f"{folder}/{path.name}", hashlib.md5(data).hexdigest()))

    body = ",\n".join(f'    "{n}"="{d}"' for n, d in rows)
    out = (
        "# scripts-ros :: manifest.rsc\n"
        "# GENERATED by tools/gen_manifest.py -- do not edit by hand.\n"
        "# md5 of every updatable file, so the router can detect an upstream\n"
        "# change with a single fetch instead of downloading each script.\n"
        "\n"
        ":global mManifest {\n" + body.replace(",\n", ";\n") + "\n}\n"
    )
    (ROOT / "manifest.rsc").write_text(out, newline="")
    print(f"manifest.rsc: {len(rows)} file(s)")
    for n, d in rows:
        print(f"  {d}  {n}")


if __name__ == "__main__":
    main()
